import { CardData } from "./types";

export const cards: CardData[] = [
  {
    id: "habakiri",
    name: "Ame no Habakiri no Mitsurugi",
    apiId: 13332685,
    archetype: "Mitsurugi",
    kind: "monster",
    race: "Reptile",
    level: 8,
    cardType: "Ritual Monster",
    tags: ["ritual", "starter", "reptile"],
    summary: "Starter principal. Revela desde mano, invoca un Mitsurugi desde deck y tributa.",
    actions: [
      {
        id: "habakiri-summon-small",
        label: "Reveal: special summon Mitsurugi from deck",
        type: "specialSummon",
        from: "deck",
        to: "field",
        target: { archetype: "Mitsurugi", kind: "monster", from: "deck", to: "field" },
        note: "Normalmente trae Saji para buscar magia/trampa.",
      },
      {
        id: "habakiri-tribute",
        label: "Then tribute 1 monster you control",
        type: "tribute",
        from: "field",
        to: "graveyard",
        target: { kind: "monster", from: "field", to: "graveyard", text: "Monster you control" },
      },
      {
        id: "habakiri-tribute-trigger",
        label: "If tributed: search Mitsurugi card",
        type: "search",
        from: "deck",
        to: "hand",
        target: { archetype: "Mitsurugi", from: "deck", to: "hand" },
      },
      {
        id: "habakiri-revive-self",
        label: "If properly summoned: revive itself",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { cardId: "habakiri", from: "graveyard", to: "field" },
        condition: { type: "single", label: "Habakiri was properly Ritual Summoned first" },
      },
    ],
  },
  {
    id: "murakumo",
    name: "Ame no Murakumo no Mitsurugi",
    apiId: 19899073,
    archetype: "Mitsurugi",
    kind: "monster",
    race: "Reptile",
    level: 8,
    cardType: "Ritual Monster",
    tags: ["ritual", "board wipe", "reptile"],
    summary: "Interrupción principal. Al ser invocado destruye todos los monstruos del rival.",
    actions: [
      {
        id: "murakumo-summon-wipe",
        label: "On special summon: destroy opponent monsters",
        type: "destroy",
        target: { text: "All monsters opponent controls" },
      },
      {
        id: "murakumo-effect-negate-discard",
        label: "Opponent effect: discard or negate",
        type: "negate",
        target: { text: "Opponent activated effect" },
      },
      {
        id: "murakumo-tribute-trigger",
        label: "If tributed: search Mitsurugi card",
        type: "search",
        from: "deck",
        to: "hand",
        target: { archetype: "Mitsurugi", from: "deck", to: "hand" },
      },
      {
        id: "murakumo-revive-self",
        label: "If properly summoned: revive itself",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { cardId: "murakumo", from: "graveyard", to: "field" },
        condition: { type: "single", label: "Murakumo was properly Ritual Summoned first" },
      },
      {
        id: "link-summon",
        label: "Link Summon using Murakumo",
        type: "linkSummon",
        from: "extraDeck",
        to: "field",
        target: { kind: "extra", from: "extraDeck", to: "field", text: "Link Monster" },
      },
    ],
  },
  {
    id: "futsu",
    name: "Futsu no Mitama no Mitsurugi",
    apiId: 55397172,
    archetype: "Mitsurugi",
    kind: "monster",
    race: "Reptile",
    level: 8,
    cardType: "Ritual Monster",
    tags: ["ritual", "revive", "reptile"],
    summary: "Motor defensivo. Cuando el rival invoca especial, revive Reptiles del GY.",
    actions: [
      {
        id: "futsu-revive-reptile",
        label: "Opponent special summons: revive Reptile",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { kind: "monster", race: "Reptile", from: "graveyard", to: "field" },
        condition: { type: "single", label: "Opponent Special Summons a monster" },
      },
      {
        id: "futsu-tribute-trigger",
        label: "If tributed: search Mitsurugi card",
        type: "search",
        from: "deck",
        to: "hand",
        target: { archetype: "Mitsurugi", from: "deck", to: "hand" },
      },
      {
        id: "futsu-revive-self",
        label: "If properly summoned: revive itself",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { cardId: "futsu", from: "graveyard", to: "field" },
        condition: { type: "single", label: "Futsu was properly Ritual Summoned first" },
      },
    ],
  },
  {
    id: "saji",
    name: "Saji no Mitsurugi",
    apiName: "Mitsurugi no Mikoto, Saji",
    apiId: 18176525,
    archetype: "Mitsurugi",
    kind: "monster",
    race: "Reptile",
    level: 4,
    cardType: "Effect Monster",
    tags: ["searcher", "spell trap", "reptile"],
    summary: "Busca magia/trampa Mitsurugi al ser invocado o tributado.",
    actions: [
      {
        id: "saji-search-spell-trap",
        label: "Summoned/tributed: search Mitsurugi Spell/Trap",
        type: "search",
        from: "deck",
        to: "hand",
        target: { archetype: "Mitsurugi", from: "deck", to: "hand", text: "Mitsurugi Spell/Trap" },
      },
      {
        id: "xyz-summon",
        label: "Xyz Summon Rank 4",
        type: "xyzSummon",
        from: "extraDeck",
        to: "field",
        target: { kind: "extra", from: "extraDeck", to: "field", text: "Rank 4 Xyz Monster" },
      },
    ],
  },
  {
    id: "aramasa",
    name: "Aramasa no Mitsurugi",
    apiName: "Mitsurugi no Mikoto, Aramasa",
    apiId: 40543231,
    archetype: "Mitsurugi",
    kind: "monster",
    race: "Reptile",
    level: 4,
    cardType: "Effect Monster",
    tags: ["searcher", "monster", "reptile"],
    summary: "Busca monstruos Mitsurugi al ser invocado o tributado.",
    actions: [
      {
        id: "normal-summon",
        label: "Normal Summon Aramasa",
        type: "normalSummon",
        from: "hand",
        to: "field",
        target: { cardId: "aramasa", from: "hand", to: "field" },
      },
      {
        id: "aramasa-search-monster",
        label: "Summoned/tributed: search Mitsurugi monster",
        type: "search",
        from: "deck",
        to: "hand",
        target: { archetype: "Mitsurugi", kind: "monster", from: "deck", to: "hand" },
      },
    ],
  },
  {
    id: "kusanagi",
    name: "Kusanagi no Mitsurugi",
    apiName: "Mitsurugi no Mikoto, Kusanagi",
    apiId: 82782870,
    archetype: "Mitsurugi",
    kind: "monster",
    race: "Reptile",
    level: 4,
    cardType: "Effect Monster",
    tags: ["recover", "reptile"],
    summary: "Recupera cartas Mitsurugi desde GY o banished.",
    actions: [
      {
        id: "kusanagi-recover",
        label: "Summoned/tributed: recover Mitsurugi from GY/banished",
        type: "recover",
        from: "graveyard",
        to: "hand",
        target: { archetype: "Mitsurugi", from: "any", to: "hand", text: "Mitsurugi card in GY or banished" },
      },
    ],
  },
  {
    id: "ritual",
    name: "Mitsurugi Ritual",
    apiId: 81560239,
    archetype: "Mitsurugi",
    kind: "spell",
    cardType: "Ritual Spell",
    tags: ["ritual spell", "engine"],
    summary: "Motor principal. Ritual Summon desde mano o deck y puede mandar materiales desde deck.",
    actions: [
      {
        id: "ritual-from-hand",
        label: "Ritual summon Reptile Ritual from hand",
        type: "ritualSummon",
        from: "hand",
        to: "field",
        target: { kind: "monster", race: "Reptile", level: 8, from: "hand", to: "field", text: "Reptile Ritual Monster" },
      },
      {
        id: "ritual-material-from-deck",
        label: "Use Reptile materials from hand/deck/field",
        type: "tribute",
        from: "deck",
        to: "graveyard",
        target: { kind: "monster", race: "Reptile", from: "deck", to: "graveyard", text: "Up to 2 Reptiles whose levels equal ritual monster" },
      },
      {
        id: "ritual-from-deck",
        label: "Ritual summon Reptile Ritual from deck",
        type: "ritualSummon",
        from: "deck",
        to: "field",
        target: { kind: "monster", race: "Reptile", level: 8, from: "deck", to: "field", text: "Reptile Ritual Monster" },
      },
    ],
  },
  {
    id: "mirror",
    name: "Mitsurugi Mirror",
    apiId: 49721684,
    archetype: "Mitsurugi",
    kind: "spell",
    cardType: "Ritual Spell",
    tags: ["ritual spell", "grind"],
    summary: "Ritual Summon desde mano o GY. Sirve para reciclar rituales ya usados.",
    actions: [
      {
        id: "mirror-ritual-from-gy",
        label: "Ritual summon Reptile Ritual from hand/GY",
        type: "ritualSummon",
        from: "graveyard",
        to: "field",
        target: { kind: "monster", race: "Reptile", level: 8, from: "any", to: "field", text: "Reptile Ritual Monster in hand or GY" },
      },
      {
        id: "mirror-shuffle-back",
        label: "Shuffle itself back when big Mitsurugi is tributed",
        type: "recover",
        from: "graveyard",
        to: "deck",
        target: { cardId: "mirror", from: "graveyard", to: "deck" },
      },
    ],
  },
  {
    id: "prayers",
    name: "Mitsurugi Prayers",
    apiId: 45171524,
    archetype: "Mitsurugi",
    kind: "spell",
    cardType: "Quick-Play Spell",
    tags: ["searcher", "revive", "extender"],
    summary: "Busca monstruo Mitsurugi o revive. Si tributás, hace ambas.",
    actions: [
      {
        id: "prayers-search",
        label: "Add Mitsurugi monster",
        type: "search",
        from: "deck",
        to: "hand",
        target: { archetype: "Mitsurugi", kind: "monster", from: "deck", to: "hand" },
      },
      {
        id: "prayers-revive",
        label: "Pay 800: special summon Mitsurugi from hand/GY",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { archetype: "Mitsurugi", kind: "monster", from: "any", to: "field" },
      },
      {
        id: "prayers-both",
        label: "If you tribute Reptile: search + revive",
        type: "enable",
        target: { text: "Both effects become available" },
        condition: { type: "single", label: "Tribute 1 Reptile from hand or field" },
      },
    ],
  },
  {
    id: "magatama",
    name: "Mitsurugi Magatama",
    apiId: 76725398,
    archetype: "Mitsurugi",
    kind: "spell",
    cardType: "Quick-Play Spell",
    tags: ["interaction", "tribute"],
    summary: "Tributa Reptile para destruir una carta boca arriba del rival. También puede ritual summon.",
    actions: [
      {
        id: "magatama-pop",
        label: "Tribute Reptile: destroy face-up card",
        type: "destroy",
        target: { text: "1 face-up card opponent controls" },
        condition: { type: "single", label: "Tribute 1 Reptile monster" },
      },
      {
        id: "magatama-ritual",
        label: "Ritual summon Mitsurugi from hand using field",
        type: "ritualSummon",
        from: "hand",
        to: "field",
        target: { archetype: "Mitsurugi", kind: "monster", from: "hand", to: "field", text: "Mitsurugi Ritual Monster" },
      },
    ],
  },
  {
    id: "purification",
    name: "Mitsurugi Great Purification",
    apiId: 17954937,
    archetype: "Mitsurugi",
    kind: "trap",
    cardType: "Normal Trap",
    tags: ["negate", "revive", "interaction"],
    summary: "Omni-negate tributando Reptile lvl 5+. Desde GY revive un Reptile y tributa otro.",
    actions: [
      {
        id: "purification-negate",
        label: "Tribute lvl 5+ Reptile: negate and destroy",
        type: "negate",
        target: { text: "Opponent card/effect" },
        condition: { type: "single", label: "Tribute 1 Level 5 or higher Reptile" },
      },
      {
        id: "purification-gy-revive",
        label: "GY effect: revive Reptile, then tribute another monster",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { kind: "monster", race: "Reptile", from: "graveyard", to: "field" },
      },
      {
        id: "set-card",
        label: "Set Great Purification",
        type: "setCard",
        from: "hand",
        to: "field",
        target: { cardId: "purification", from: "hand", to: "field" },
      },
    ],
  },
  {
    id: "night-sword-serpent",
    name: "Night Sword Serpent",
    apiId: 20295753,
    kind: "monster",
    race: "Reptile",
    level: 4,
    cardType: "Effect Monster",
    tags: ["extender", "reptile"],
    summary: "Si va al GY por efecto de carta, se invoca solo. Excelente material para Ritual.",
    actions: [
      {
        id: "night-sword-revive",
        label: "Sent to GY by card effect: revive itself",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { cardId: "night-sword-serpent", from: "graveyard", to: "field" },
      },
    ],
  },
  {
    id: "manju",
    name: "Manju of the Ten Thousand Hands",
    apiId: 95492061,
    kind: "monster",
    level: 4,
    cardType: "Effect Monster",
    tags: ["normal summon", "searcher"],
    summary: "Normal summon que busca Ritual Monster o Ritual Spell.",
    actions: [
      {
        id: "manju-search",
        label: "Normal summon: search Ritual Monster or Ritual Spell",
        type: "search",
        from: "deck",
        to: "hand",
        target: { from: "deck", to: "hand", text: "Ritual Monster or Ritual Spell" },
      },
    ],
  },
  {
    id: "pre-prep",
    name: "Pre-Preparation of Rites",
    apiId: 13048472,
    kind: "spell",
    cardType: "Normal Spell",
    tags: ["starter", "searcher"],
    summary: "Busca Mirror + un ritual mencionado por Mirror. En Mitsurugi normalmente busca Habakiri.",
    actions: [
      {
        id: "preprep-search-mirror",
        label: "Search Ritual Spell that lists a monster",
        type: "search",
        from: "deck",
        to: "hand",
        target: { cardId: "mirror", from: "deck", to: "hand" },
      },
      {
        id: "preprep-search-listed",
        label: "Search listed Ritual Monster",
        type: "search",
        from: "deck",
        to: "hand",
        target: { kind: "monster", from: "deck", to: "hand", text: "Habakiri / Murakumo / Futsu listed on Mirror" },
      },
    ],
  },
  {
    id: "dugares",
    name: "Number 60: Dugares the Timeless",
    apiId: 66011101,
    kind: "extra",
    race: "Fiend",
    level: 4,
    cardType: "Xyz Monster",
    tags: ["xyz", "rank 4", "draw", "extension"],
    summary: "Rank 4 genérico. Puede desacoplar 2 materiales para robar 2 y descartar 1.",
    actions: [
      {
        id: "dugares-draw-discard",
        label: "Detach 2: draw 2 and discard 1",
        type: "enable",
        target: { text: "Draw 2 cards, then discard 1" },
      },
    ],
  },
  {
    id: "dyna-mondo",
    name: "Dyna Mondo",
    apiId: 73898890,
    kind: "extra",
    cardType: "Link Monster",
    tags: ["link", "ritual support", "revive"],
    summary: "Link 2 para rituales. En turno rival tributa y revive un Ritual Monster del GY.",
    actions: [
      {
        id: "dyna-revive",
        label: "Opponent turn: tribute itself, revive Ritual Monster",
        type: "revive",
        from: "graveyard",
        to: "field",
        target: { kind: "monster", from: "graveyard", to: "field", text: "Ritual Monster" },
        condition: {
          type: "and",
          label: "Dyna Mondo + Ritual in GY",
          conditions: [
            { type: "single", label: "Dyna Mondo on field" },
            { type: "single", label: "Ritual Monster in GY" },
          ],
        },
      },
    ],
  },
  {
    id: "ip",
    name: "I:P Masquerena",
    apiId: 65741786,
    kind: "extra",
    cardType: "Link Monster",
    tags: ["link", "interaction"],
    summary: "Permite hacer Link Summon durante el turno del rival.",
    actions: [
      {
        id: "ip-link",
        label: "Opponent Main Phase: Link Summon",
        type: "linkSummon",
        from: "field",
        to: "extraDeck",
        target: { kind: "extra", from: "extraDeck", to: "field", text: "Link Monster using I:P" },
      },
    ],
  },
  {
    id: "number-90",
    name: "Number 90: Galaxy-Eyes Photon Lord",
    apiId: 8165596,
    kind: "extra",
    race: "Warrior",
    level: 8,
    cardType: "Xyz Monster",
    tags: ["xyz", "rank 8", "negate", "interaction"],
    summary: "Rank 8 genérico. Puede negar efectos de monstruo y presionar con materiales Photon/Galaxy.",
    actions: [
      {
        id: "number-90-monster-negate",
        label: "Detach material: negate monster effect",
        type: "negate",
        target: { text: "Opponent monster effect" },
      },
    ],
  },
  {
    id: "sp",
    name: "S:P Little Knight",
    apiId: 29301450,
    kind: "extra",
    cardType: "Link Monster",
    tags: ["link", "banish", "interaction"],
    summary: "Interrupción genérica. Al ser invocada puede banish una carta.",
    actions: [
      {
        id: "sp-banish",
        label: "On Link Summon: banish 1 card",
        type: "destroy",
        target: { text: "Banish 1 card on field or GY" },
      },
    ],
  },
];
